#app
server:
    port: 8082

MYSQL_HOST: 182.92.102.51

#spring
spring:
  devtools:
    restart:
      enabled: false
# DATABASE CONFIG
  datasource:
      #如果mybatis时区不正确可以使用在mysql.url后加上 serverTimezone=Hongkong 解决
      url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/dataspider?useUnicode=true&characterEncoding=UTF8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: "!QAZ2wsx"
      # 使用druid数据源
      #type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  # 解决Spring 返回json时间不正确问题
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8    #或UTC
logging:
  level:
    com:
      looedu:
        mapper: debug


#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.ssbc.nmg.dataspider.dao
  #typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    #刷新mapper 调试神器
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: false
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: true
      #自定义填充策略接口实现
      #meta-object-handler: com.baomidou.springboot.xxx
      #自定义SQL注入器
      #sql-injector: com.baomidou.springboot.xxx


  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false